Task.WebApplication/Controllers/ExamController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Task.Core.Dtos;
using Task.Core.Entities;
using Task.Services.ExamService;
using Task.Services.StudentService;
using Task.Services.UserService;

namespace Task.WebApplication.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ExamController : Controller
    {
        private readonly IExamService _examService;
        private readonly IStudentService _studentService;
        private readonly IUserService _userService;

        public ExamController(IExamService examService , IStudentService studentService , IUserService userService) 
        {
            _examService = examService;
            _studentService = studentService;
            _userService = userService;
        }
        public async Task<IActionResult> Index()
        {
            ViewBag.students = new SelectList(await _studentService.GetAllStudents() , "Id" , "UserName");
            return View(await _examService.GetAllExams());
        }

        public async Task<IActionResult> AddExam()
        {
            ViewBag.Teachers = new SelectList(await _userService.GetUsersInRole("Teacher"), "Id", "UserName");
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> AddExam(Exam exam)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Teachers = new SelectList(await _userService.GetUsersInRole("Teacher"), "Id", "UserName");
                return View();
            }
            
            Exam Exam =  await _examService.AddExam(exam);

            if (Exam != null)
            {
                return RedirectToAction("Questions" , new { examId = Exam.Id});
            }

            ViewBag.Teachers = new SelectList(await _userService.GetUsersInRole("Teacher"), "Id", "UserName");
            return View();
        }

        public async Task<IActionResult> Questions(int examId)
        {
            ViewData["ExamId"] = examId;
            var questions = await _examService.GetExamQuestions(examId);
            return View(questions);
        }
        [HttpPost]
        public async Task<IActionResult> AddQuestion(Question question , QuestionAnswerDto questionAnswerDto)
        {
            if (await _examService.IsPermittedToAdd(question.Mark, question.ExamId))
            {
                Question questionAdded = await _examService.AddQuestionToExam(question, question.ExamId);
                if (questionAdded != null)
                {
                    await _examService.AddOrEditAnswerToQuestion(questionAdded.Id, questionAnswerDto);
                }
            }

            return RedirectToAction("Questions" , new { examId = question.ExamId });
        }

        [HttpPost]
        public async Task<IActionResult> EditQuestion(Question question)
        {
            await _examService.EditQuestionToExam(question);
            return RedirectToAction("Questions", new { examId = question.ExamId });
        }


        public async Task<IActionResult> RemoveQuestion(int questionId , int ExamId)
        {
            await _examService.RemoveQuestion(questionId);
            return RedirectToAction("Questions", new { examId = ExamId });
        }

        public async Task<IActionResult> AssignStudents(List<int> students, int examId)
        {
            int res = await _studentService.AssignStudentToExam(students, examId);
            return RedirectToAction("Index");
        }

    }
}

Task.WebApplication/Views/Exam/AddExam.cshtml
@model Exam
@{
    ViewData["Title"] = "AddExam";
}

<h1>Add Exam</h1>

<div class="row">
    <div class="col-md-6">
        <form asp-action="AddExam" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Title">Exam Title</label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="TotalMarks">Tatal Mark</label>
                <input asp-for="TotalMarks" class="form-control" />
                <span asp-validation-for="TotalMarks" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Duration">Duration In Minuts</label>
                <input asp-for="Duration" class="form-control" />
                <span asp-validation-for="Duration" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="TeacherId">Exam Teacher</label>
                <select asp-for="TeacherId" class="form-control" asp-items="@ViewBag.Teachers"></select>
                <span asp-validation-for="TeacherId" class="text-danger"></span>
            </div>


            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</div>




@section scripts{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Task.WebApplication/Views/Exam/AddQuestions.cshtml
@model Question

@{
    ViewData["Title"] = "AddQuestions";
}

<h1>Add Questions To Exam</h1>

Task.WebApplication/Views/Exam/Index.cshtml
@model List<Exam>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>
<a asp-action="AddExam" class="btn btn-primary">
    Add Exam
</a>

<table class="table" id="pageTable">
    <thead>
        <tr>
            <th>Exam Number</th>
            <th>Exam Title</th>
            <th>Exam Duration</th>
            <th>Exam Teacher</th>
            <th>Exam Questions</th>
            <th>Assign Student To Exam</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Title</td>
                <td>@item.Duration</td>
                <td>@item.Teacher.FirstName @item.Teacher.LastName</td>
                <td>
                    <a asp-action="Questions" asp-route-examId="@item.Id">Exam Questions</a>
                </td>
                <td>
                    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal_@item.Id">
                        Assign Students
                    </button>
                </td>
            </tr>
            <!-- Modal -->
            <div class="modal fade" id="exampleModal_@item.Id" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <form asp-action="AssignStudents" asp-controller="Exam" asp-route-examId="@item.Id" method="post">
                            <div class="modal-body">
                                <div class="form-group">
                                    <label for="students">Question Type</label>
                                    <select name="students" id="students" class="form-control" multiple asp-items="@ViewBag.students"> </select>
                                </div>
                            </div>

                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                <button type="submit" class="btn btn-primary">Assign</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

        }
    </tbody>
</table>

Task.WebApplication/Views/Exam/Questions.cshtml
@model List<Question>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

@Html.Partial("_AddQuestion" , new Question{ ExamId = ViewBag.ExamId })

<table class="table" id="pageTable">
    <thead>
        <tr>
            <th>Question Number</th>
            <th>Qusetion Type</th>
            <th>Question Text</th>
            <th>Question Mark</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.QuestionType</td>
                <td>@item.Text</td>
                <td>@item.Mark</td>
                <td>
                    @Html.Partial("_EditQuestion", item)
                    <a asp-action="RemoveQuestion" asp-route-questionId="@item.Id" asp-route-ExamId="@item.ExamId" class="btn btn-danger">Remove Question</a>
                    @Html.Partial("_QuestionAnswers",item.QuestionsAnswers)
                </td>
            </tr>
        }
    </tbody>
</table>

@section scripts{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

    <script>
        $(document).on('change', '#QuestionType', function () {
            let selectValue = $("#QuestionType").val();
            var counter = $('#modalTable tr').length;
            if (selectValue == 0) {
                $("#answerTable tr").remove();
                $('#answerTable').append(`<tr>
                                    <th class='text-center px-2'>AnswerText</th>
                                    <th class='text-center px-2'>Is Correct</th>
                                </tr>
                                <tr>
                                    <td class='text-center px-2'>
                                        <input type="text" class="form-control" disabled value="False" />
                                        <input type="hidden" class="form-control" required value="True" name="QuestionText1" placeholder="Answer 1 text" />
                                    </td>
                                    <td class='text-center px-2'>
                                        <input type="radio" required name="IsCorrect" Value="Q1"/>
                                    </td>
                                </tr>
                                <tr>
                                    <td class='text-center px-2'>
                                        <input type="text" class="form-control" disabled value="False" />
                                        <input type="hidden" class="form-control" required value="False" name="QuestionText2" placeholder="Answer 2 text" />
                                    </td>
                                    <td class='text-center px-2'>
                                        <input type="radio" required name="IsCorrect" Value="Q2" />
                                    </td>
                                </tr>`);
            }
            else if (selectValue == 2) {
                $("#answerTable tr").remove();
                $('#answerTable').append(`<tr>
                                        <th class='text-center px-2'>AnswerText</th>
                                        <th class='text-center px-2'>Is Correct</th>
                                    </tr>
                                    <tr>
                                        <td class='text-center px-2'>
                                            <input type="text" class="form-control" required name="QuestionText1" placeholder="Answer 1 text" />
                                        </td>
                                        <td class='text-center px-2'>
                                            <input type="radio" required name="IsCorrect" Value="Q1"/>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class='text-center px-2'>
                                            <input type="text" class="form-control" required name="QuestionText2" placeholder="Answer 2 text" />
                                        </td>
                                        <td class='text-center px-2'>
                                            <input type="radio" required name="IsCorrect" Value="Q2" />
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class='text-center px-2'>
                                            <input type="text" class="form-control" required name="QuestionText3" placeholder="Answer 3 text" />
                                        </td>
                                        <td class='text-center px-2'>
                                            <input type="radio" required name="IsCorrect" Value="Q3"/>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td class='text-center px-2'>
                                            <input type="text" class="form-control" required name="QuestionText4" placeholder="Answer 4 text" />
                                        </td>
                                        <td class='text-center px-2'>
                                            <input type="radio" required name="IsCorrect" Value="Q4" />
                                        </td>
                                    </tr>
                                    `);
            }
            else if (selectValue == 4) {
                $("#answerTable tr").remove();
                $('#answerTable').append(`<tr>
                                        <th class='text-center px-2'>AnswerText</th>
                                        <th class='text-center px-2'>Is Correct</th>
                                    </tr>
                                    <tr>
                                        <td class='text-center px-2'>
                                            <input type="text" class="form-control" required name="QuestionText1" placeholder="Answer text" />
                                        </td>
                                        <td class='text-center px-2'>
                                            <input type="radio" required name="IsCorrect" Value="Q1"/>
                                        </td>
                                    </tr>
                                    `);
            }
            else {
                $("#answerTable tr").remove();
                $('#answerTable').append(`<tr>
                                        <th class='text-center px-2'>AnswerText</th>
                                        <th class='text-center px-2'>Is Correct</th>
                                    </tr>
                                    <tr>
                                        <td class='text-center px-2'>
                                            <textarea type="text" class="form-control" required name="QuestionText1" placeholder="Answer text"></textarea>
                                        </td>
                                        <td class='text-center px-2'>
                                            <input type="radio" required name="IsCorrect" Value="Q1"/>
                                        </td>
                                    </tr>
                                    `);
            }
        });
        $(document).ready(function () {
            $('#QuestionType').trigger('change');
        });
    </script>

}